apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8000'
    spec:
      containers:
        - name: otus-app
          image: 100callstoeurop/otus-homework:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 8000
          env:
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: PG_USERNAME
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: PG_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: PG_DATABASE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: otus-app-cm
                  key: PORT
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: otus-app-cm
                  key: PG_HOST
            - name: AT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: AT_SECRET
            - name: RT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: RT_SECRET
            - name: AT_TIME
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: AT_TIME
            - name: RT_TIME
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: RT_TIME
