apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
        - name: my-database
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: PG_DATABASE

            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: PG_USERNAME

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-credentials
                  key: PG_PASSWORD

          volumeMounts:
            - mountPath: /var/lib/postgres/data
              name: db-data

            - mountPath: /docker-entrypoint-initdb.d
              name: postgresdb-loadsql
      volumes:
        - name: postgresdb-loadsql
          configMap:
            name: database-cm

        - name: db-data
          persistentVolumeClaim:
            claimName: pvc-db