apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: otus-app
        image: 100callstoeurop/otus
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
