apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
    spec:
      containers:
      - name: otus-app
        image: 100callstoeurop/otus-homework:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret-credentials
                  key: PORT

            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret-credentials
                  key: PG_PORT
            
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret-credentials
                  key: PG_HOST

            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secret-credentials
                  key: PG_DATABASE

            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret-credentials
                  key: PG_USERNAME

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-credentials
                  key: PG_PASSWORD
