version: '3.9'

services:
  auth:
    build: ./app/auth
    container_name: auth
    command: dist/apps/auth/main
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    env_file:
      - './envs/.auth.env'
    networks:
      otus-net:

  billing:
    build: ./app/billing
    container_name: billing
    command: dist/apps/auth/billing
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    env_file:
      - './envs/.billing.env'
    networks:
      otus-net:

  notification:
    build: ./app/notification
    container_name: notification
    command: dist/apps/auth/notification
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    env_file:
      - './envs/.notification.env'
    networks:
      otus-net:

  order:
    build: ./app/order
    container_name: order
    command: dist/apps/auth/order
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    env_file:
      - './envs/.order.env'
    networks:
      otus-net:

  nginx:
    image: nginx:latest
    container_name: nginx_product
    ports:
      - '8010:8010'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - billing
      - notification
      - order
    networks:
      otus-net:

networks:
  otus-net:
    name: otus-net
