version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    container_name: auth
    command: yarn start-auth:dev
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    env_file:
      - './apps/auth/.env'
    networks:
      otus-net:

  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    container_name: billing
    command: yarn start-billing:dev
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    env_file:
      - './apps/billing/.env'
    networks:
      otus-net:

  notification:
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    container_name: notification
    command: yarn start-notification:dev
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    env_file:
      - './apps/notification/.env'
    networks:
      otus-net:

  order:
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
      target: development
    container_name: order
    command: yarn start-order:dev
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
    env_file:
      - './apps/order/.env'
    networks:
      otus-net:

  nginx:
    image: nginx:latest
    container_name: nginx_product
    ports:
      - '8010:8010'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - billing
      - notification
      - order
    networks:
      otus-net:

networks:
  otus-net:
    name: otus-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
