{
 "title": "OTUS-APP",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "API LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{method!=\"GET\"}[10m])) by(le)) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{method!=\"GET\"}[10m])) by(le))  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{method!=\"GET\"}[10m])) by(le))  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket{method!=\"GET\"}[10m])) by(le)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[10m])) by(le))  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[10m])) by(le)) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[10m])) by(le))  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[10m])) by(le))  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~'2..'}[10m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~'2..'}[10m])) by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API 500 ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~\"5..\"}[10m])) by(status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX 500 ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{status=~'5..'}[10m])) by(status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}