apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-ingress
  labels:
    name: otus-ingress
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - pathType: Exact
        path: "/v1"
        backend:
          service:
            name: otus-service
            port: 
              number: 80
