apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /otusapp/.*
        pathType: Mixed
        backend:
          service:
            name: otus-app
            port:
              number: 80
      - path: /health
        pathType: Exact
        backend:
          service:
            name: otus-app
            port:
              number: 80
  ingressClassName: nginx