apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
spec:
  completions: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: otus-app
        image: 100callstoeurop/otus-homework:latest
        command: ["sh", "-c", "yarn migration drop && yarn migration:create && yarn migration:migrate"]
        env:
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret-credentials
              key: PG_USERNAME
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret-credentials
              key: PG_PASSWORD
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret-credentials
              key: PG_DATABASE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: otus-app-cm
              key: PORT
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: otus-app-cm
              key: PG_HOST
        volumeMounts:
        - name: postgresql-data
          mountPath: /data/volume
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data-claim
