# define default database user, name, and password for PostgreSQL deployment
auth:
  username: "postgres"
  password: "Dusmodus"
  database: "otus"

# The postgres helm chart deployment will be using PVC postgresql-data-claim
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-data-claim"