apiVersion: batch/v1 
kind: Job
metadata:
  name: create-db-job
spec:
  completions: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: create-db
        image: postgres:16
        command: ["sh", "-c", "set -e; psql -h ${PG_HOST} -U postgres -d postgres -c \"CREATE DATABASE auth;\" "] 
        env:
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: auth-cm
              key: PG_HOST
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret-credentials
              key: PG_PASSWORD