prometheus:
  pushgateway: 
    enabled: false

grafana:
  service:
    type: NodePort

postgresql:
  auth:
    username: "postgres"
    password: "Deusmodus"
    database: "postgres"
  databases:
    - name: auth
      encoding: UTF8
    - name: billing
      encoding: UTF8
    - name: notification
      encoding: UTF8
    - name: order
      encoding: UTF8
  
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-data-claim"

ingress-nginx:
  controller:
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/port: "10254"
          prometheus.io/scrape: "true"

kafka:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard
    replicaCount: 3
    zookeeper:
       enabled: true
