prometheus:
  pushgateway: 
    enabled: false

grafana:
  service:
    type: NodePort

postgresql:
  auth:
    username: "postgres"
    password: "Deusmodus"
    database: "postgres"
  
primary:
  persistence:
    enabled: true
    existingClaim: "postgresql-data-claim"

ingress-nginx:
  controller:
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/port: "10254"
          prometheus.io/scrape: "true"

kafka:
  enabled: true
  controller:
    replicaCount: 0
    automountServiceAccountToken: true
  broker:
    replicaCount: 2
    persistence:
      size: 1Gi
    automountServiceAccountToken: true
  kraft:
    enabled: false
  zookeeper:
    enabled: true
    persistence:
      size: 1Gi
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
