prometheus:
  pushgateway: 
    enabled: false

grafana:
  service:
    type: NodePort

ingress-nginx:
  controller:
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/port: "10254"
          prometheus.io/path: "api/metrics"
          prometheus.io/scrape: "true"

  externalAccess:
    enabled: true
    broker:
      service:
        type: LoadBalancer
        ports:
          external: 9094
    controller:
      service:
        type: LoadBalancer
        containerPorts:
          external: 9094

rabbitmq:
  auth:
    username: "admin"
    password: "admin"



