apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouses
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warehouses
  template:
    metadata:
      labels:
        app: warehouses
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /api/metrics
        prometheus.io/port: '10254'
    spec:
      containers:
        - name: warehouses
          image: 100callstoeurop/otus-app_warehouse
          ports:
            - containerPort: 8005
          env:
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: warehouse-secret-credentials
                  key: PG_USERNAME
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warehouse-secret-credentials
                  key: PG_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: warehouse-secret-credentials
                  key: PG_DATABASE
            - name: AT_SECRET
              valueFrom:
                secretKeyRef:
                  name: warehouse-secret-credentials
                  key: AT_SECRET
            - name: AT_TIME
              valueFrom:
                secretKeyRef:
                  name: warehouse-secret-credentials
                  key: AT_TIME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: warehouse-cm
                  key: PORT
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: warehouse-cm
                  key: PG_HOST
            - name: AMQP_URI
              valueFrom:
                configMapKeyRef:
                  name: warehouse-cm
                  key: AMQP_URI
