apiVersion: v1
kind: Secret
metadata:
  name: auth-secret-credentials
data:
  PG_USERNAME: cG9zdGdyZXM=
  PG_PASSWORD: RGV1c21vZHVz
  PG_DATABASE: cG9zdGdyZXM=
  AT_SECRET: QSYvfVo1N00oMmhOZz07TEU/fl1ZdDIyUzUoeVo8dmNaVEEzTi0oJD4yajpaZVgtQkdmdGFWa2ApaktQfnI/LGprKUVNYmd0KmtX
  RT_SECRET: QiYvfVo1OE0oMmhOcz07TEU/fl1IR1JNUzUoeVo8dmNaVEEzTi0oJD4yajozMzMtQkdmdGFWa2ApaktQfnE/LGprKUVNYmd0ZVBz
  AT_TIME: MTAwMDA=
  RT_TIME: MTAwMDA=
