apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: svc-app-monitor
  labels:
    app: svc-app
spec:
  endpoints:
  - port: 9093
    scheme: http
    path: /metrics
    interval: 60s
  selector:
    matchLabels:
      app: svc-app
  namespaceSelector:
    matchNames:
    - production

