apiVersion: batch/v1
kind: Job
metadata:
  name: billing-migration-job
spec:
  completions: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: billings
        image: 100callstoeurop/otus-app_billing
        command: ["sh", "-c", "yarn migration-billing:migrate"]
        env:
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: billing-secret-credentials
              key: PG_USERNAME
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: billing-secret-credentials
              key: PG_PASSWORD
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: billing-secret-credentials
              key: PG_DATABASE
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: billing-cm
              key: PORT
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: billing-cm
              key: PG_HOST
        volumeMounts:
        - name: postgresql-billing-data
          mountPath: /data/volume/billing
      volumes:
      - name: postgresql-billing-data
        persistentVolumeClaim:
          claimName: data-billing-postgresql-0
