apiVersion: apps/v1
kind: Deployment
metadata:
  name: billings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billings
  template:
    metadata:
      labels:
        app: billings
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /api/metrics
        prometheus.io/port: '10254'
    spec:
      containers:
        - name: billings
          image: 100callstoeurop/otus-app_billing
          ports:
            - containerPort: 8001
          env:
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: billing-secret-credentials
                  key: PG_USERNAME
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-secret-credentials
                  key: PG_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: billing-secret-credentials
                  key: PG_DATABASE
            - name: AT_SECRET
              valueFrom:
                secretKeyRef:
                  name: billing-secret-credentials
                  key: AT_SECRET
            - name: AT_TIME
              valueFrom:
                secretKeyRef:
                  name: billing-secret-credentials
                  key: AT_TIME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: billing-cm
                  key: PORT
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: billing-cm
                  key: PG_HOST
            - name: AMQP_URI
              valueFrom:
                configMapKeyRef:
                  name: order-cm
                  key: AMQP_URI
