apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /api/metrics
        prometheus.io/port: '10254'
    spec:
      containers:
        - name: notifications
          image: 100callstoeurop/otus-app_notification
          ports:
            - containerPort: 8002
          env:
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret-credentials
                  key: PG_USERNAME
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret-credentials
                  key: PG_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: notification-secret-credentials
                  key: PG_DATABASE
            - name: AT_SECRET
              valueFrom:
                secretKeyRef:
                  name: notification-secret-credentials
                  key: AT_SECRET
            - name: AT_TIME
              valueFrom:
                secretKeyRef:
                  name: notification-secret-credentials
                  key: AT_TIME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: notification-cm
                  key: PORT
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: notification-cm
                  key: PG_HOST
            - name: AMQP_URI
              valueFrom:
                configMapKeyRef:
                  name: order-cm
                  key: AMQP_URI
